language: python
dist: xenial

# only intended for Linux and Mac jobs. Windows will overwrite install and script
install: python3 -m pip install tox
script: python3 -m tox

stages:
- test
- "PYPI release"
jobs:
  include:
  # linux
  - python: '3.7'
  - python: '3.6'
  - python: '3.5'

  # osx python 3.7
  - name: "Python: 3.7"
    os: osx
    # xcode 11 image comes with python 3.7
    osx_image: xcode11
    # language: python will error
    language: shell

  # osx python 3.6
  - name: "Python: 3.6"
    os: osx
    osx_image: xcode11
    language: shell
    # switch to python 3.6
    addons:
      homebrew:
        update: true
    before_install:
      - pyenv install 3.6.5
      - pyenv global 3.6.5
    # end switch

  # osx python 3.5
  - name: "Python: 3.5"
    os: osx
    osx_image: xcode11
    language: shell
    # switch to python 3.5
    addons:
      homebrew:
        update: true
    before_install:
      - pyenv install 3.5.2
      - pyenv global 3.5.2
    # end switch

  # windows python 3.7
  - name: "Python: 3.7"
    os: windows
    # language: python will error
    language: shell
    # install python 3.7
    before_install:
      - choco install python --version 3.7.4
      - python -m pip install --upgrade pip
    install: python -m pip install tox
    # On Windows, python3 does not exist
    script: python -m tox
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

  # windows python 3.6
  - name: "Python: 3.6"
    os: windows
    language: shell
    before_install:
      - choco install python --version 3.6.8
      - python -m pip install --upgrade pip
      - python -m pip install pipenv
    install: python -m pip install tox
    script: python -m tox
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

  # windows python 3.5
  - name: "Python: 3.5"
    os: windows
    language: shell
    before_install:
      - choco install python --version 3.5.4
      - python -m pip install --upgrade pip
      - python -m pip install pipenv
    install: python -m pip install tox
    script: python -m tox
    env: PATH=/c/Python35:/c/Python35/Scripts:$PATH

  - stage: "PYPI release"
    install: ''
    script: ''
    after_success: ''
    deploy:
      provider: pypi
      user: Madoshakalaka
      password:
        secure: E1iJS0oOb3EKIjdeteg9JuLoEtNeSiW6ZDwH8sM7aHpUxwFKN3PACIp4+S1sb8hsOuA0OUvy2JUHnRq8ybvmEI+8hu9dqmm/jyS2g+3Q026gPFAGEZN6J19NPMn8e7+QnpN03Dc85hEg6bbpFuzwwX27l6NrcWloRQuPZ6aG0w3HAQS4jjhpKgylbqAKbd+G+HKVahCITepkXXCdKt9dbHNCPzHkMNDtHCSdP+3LfWdQGhHBEuahTFMYn3J4NOil6TB3hR4V5DNt+qq/NIVmpVxuUihN8defe314XI7LVGLUSR9bkNt6XA4vw3HuycSN/UX2RYeBGkgtmj5hWps/4ElRp+PQy2y+osrtzuOibK+UbGICpRJQI9q/uZehCyEIxqHogVhe9SFMNFCwR87L9APRgXwJMdrKYx3oLbPEQcAdHQ5s027Ok6H0+ZBIoMQtLu1nLdTzSiGc0I/BLnH/hPBJVhuCM8fm4lxgonGHb4rhapmdwzbOmOVgtptnTofXaoLAlqTg7TcjCADU9SBjzGlTgY3EHYqTYJ3wy+mCv0MgIBDlpw1XiLM+auKnYhDvwszBZ0RDuZJ6pCi4vY57Jw/e7Q2UZWzkLpRLqJ+Dbp+EZayEWiVtEFKWlAAMxNPRErFmBpxbyY+vFjI4WM63t/tpqaCPk7E7fAUDEKaY0HM=
      on:
        tags: true